version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - contractless-dao
    read_only: false
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    networks:
      - contractless-dao
    read_only: false
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - contractless-dao
    read_only: false
    restart: always

networks:
  contractless-dao:
    name: contractless-dao


